### ISSUE TITLE
use concrete types in structs

### ISSUE THREAD

**Issue by itsdfish** [taylor-curley/HyGene.jl#1]
Hi Taylor, 

This project looks interesting. Is this a side project you are doing for fun? 

I noticed that the structs have fields with type `Any` (the default type when one is not specified). This will slow down code execution because the compiler does cannot make any guarantees about the types at run time because they could change. One approach is to specify the types directly, or to use parametric types (which provide some flexibility and make the code more terse). For example, if you have two types, you can define parametric types `T1` and `T2` and optionally place constraints on them:

```
struct MyStruct{T1<:Int,T2<:AbstractFloat}
    x1::T2
    x2::T1
    x3::T2 
end
```

Another approach is that you can use the `@concrete` macro from ConcreteStructs.jl to ensure that the types are concrete rather than abstract. In the follow example, the fields can be any concrete type:

```
@concrete struct MyStruct
    x1
    x2 
    x3
end
```
This is the most flexible. The downside is that the user might use the wrong type if it is not clear from the documentation or context.

**Comment by taylor-curley** [comment]
Hey,

I'm so sorry I'm just seeing this now! And yes - it's a side project, although I think that it has a lot of potential use for AFRL research. This is the base for the `MetaHyGene` package I was developing earlier, but never quite got to.

I did not define types because I was not sure how exactly I wanted the fields to be populated, but I also had no idea that the `@concrete` command helped with this. I'll update the code. Thank you!

**Comment by taylor-curley** [comment]
Closing this issue as the new release is completely different lol
